Add Dialect notifications
solana-labs/governance-ui pull request #1125
Opened 2022-10-26 16:21 UTC by dshuvalov

# Feature
- update dialect's packages and legacy modal notifications
- integrate Dialect notifications into hub

2022-10-28 13:55 UTC, dshuvalov commented
How it looks after pulling main branch
<img width="1524" alt="Снимок экрана 2022-10-28 в 17 53 20" src="https://user-images.githubusercontent.com/16071062/198626461-2d285be8-a03a-4395-b619-437d7715da74.png">
<img width="1536" alt="Снимок экрана 2022-10-28 в 17 55 40" src="https://user-images.githubusercontent.com/16071062/198626674-5efb909c-0b48-4d93-81fe-0b569c76579d.png">

2022-10-28 15:03 UTC, nramadas requested changes
Looks great! Just one small change requested. Thanks!

2022-10-31 08:39 UTC, dshuvalov commented on hub/providers/WalletSelector/index.tsx
> +      <_WalletProvider wallets={supportedWallets} autoConnect>
No problem. I can explain. We use WalletProvider and useWallet hook from the "@solana/wallet-adapter-react" for configuring DialectSolanaSdk from our package, we use auto connect for retrieving wallet info if a user had already signed in to Solana wallet (phantom app for example). Without this preference, user has to sign in to wallet every time

2022-10-31 08:40 UTC, dshuvalov commented on hub/components/GlobalHeader/User/DialectNotifications/Notifications.constants.ts
> +import * as anchor from '@project-serum/anchor';
Fixed. Thanks!

2022-10-31 14:51 UTC, nramadas approved these changes

2022-11-02 15:07 UTC, merged