Add Lido to treasury investments
solana-labs/governance-ui pull request #844
Opened 2022-07-12 13:21 UTC by Tataklim

2022-07-12 15:29 UTC, nramadas requested changes
Hey @Tataklim , just two small style nits, then I can merge the PR. Thanks!

2022-07-12 15:29 UTC, nramadas commented on components/TreasuryAccount/ConvertToStSol.tsx
> +            ></Textarea>
small style nit, if you could use a self-closing jsx tag instead of `</Textarea>` that would be appreciated

2022-07-12 15:29 UTC, nramadas commented on components/TreasuryAccount/ConvertToStSol.tsx
> +              ></VoteBySwitch>
same style nit here

2022-07-13 05:46 UTC, Tataklim commented
Thank you for the review [nramadas](https://github.com/nramadas)! Fixed your comment
We haven't tested it yet - can you please press the button to deploy with new changes and after testing, if everything is OK, I will write you to merge

2022-07-14 13:05 UTC, Tataklim commented
Hey [@nramadas](https://github.com/nramadas) We have tested it and everything is ok :) Ready to merge

2022-07-18 14:16 UTC, nramadas approved these changes

2022-07-18 23:14 UTC, merged