Holaplex indexer
solana-labs/governance-ui pull request #864
Opened 2022-07-15 18:20 UTC by dandlezzz

Adding the Holaplex indexer for fetching nfts

2022-07-18 14:28 UTC, kespinola commented on utils/tokens.tsx
> +  console.log({ body })
drop console log before ship.

2022-07-18 14:28 UTC, kespinola commented on utils/tokens.tsx
> +    console.log('here are the nfts', data.nfts)
drop console.log before ship.

2022-07-18 14:28 UTC, kespinola commented on hooks/useVotingPlugins.ts
> +      const votingNfts = nfts.filter((x) => getIsFromCollection(x))
```suggestion
      const votingNfts = nfts.filter(getIsFromCollection)
```

2022-07-22 18:30 UTC, dandlezzz commented on utils/tokens.tsx
> +               limit: 10000, offset: 0) {
Good question. The largest example I  was given was 300, so I'm hopeful this will work for nearly all use cases.

2022-07-22 19:39 UTC, nramadas requested changes
Hey @dandlezzz ! Noticed a small issue. When I visit a DAO, it show all of my NFTs, not just the ones relevant to the DAO. For example on https://governance-907qtch70-blockworks-foundation.vercel.app/dao/DTP, i see:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/1679892/180515458-2cde1c45-2da4-4791-8617-7d05006aab88.png">

But on prod (https://realms.today/dao/DTP), I see:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1679892/180515521-ba0554f8-adcb-4852-928e-833c13cf7027.png">

Maybe the nft list isn't being fully filtered?

2022-07-25 19:12 UTC, nramadas approved these changes

2022-07-26 09:46 UTC, abrzezinski94 commented on NftVotePlugin/store/nftPluginStore.ts
> +    votingClient._setCurrentVoterNfts(nfts)
We can't remove the filter becuase only nfts with amount === 1 can vote.

2022-07-26 21:03 UTC, nramadas requested changes
Hey @dandlezzz , I think i might have spotted another issue.

In this DAO, on prod, there seems to be an NFT in its treasury:
https://realms.today/dao/MNGO

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1679892/181111449-7054ad0f-3ddd-40e7-b8d5-2a81ada6b2b1.png">

But, in this branch, that NFT no longer shows up:
https://governance-6sstw70o3-blockworks-foundation.vercel.app/dao/MNGO

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1679892/181111494-0380bd1b-c07d-4004-9ab7-9c696b14bc27.png">

Would you mind taking a look?

2022-07-27 15:52 UTC, dandlezzz commented
Looking into this issue.

2022-07-27 15:53 UTC, dandlezzz commented
> Hey @dandlezzz , I think i might have spotted another issue.
> 
> In this DAO, on prod, there seems to be an NFT in its treasury: https://realms.today/dao/MNGO
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/1679892/181111449-7054ad0f-3ddd-40e7-b8d5-2a81ada6b2b1.png">
> 
> But, in this branch, that NFT no longer shows up: https://governance-6sstw70o3-blockworks-foundation.vercel.app/dao/MNGO
> 
> <img alt="image" width="471" src="https://user-images.githubusercontent.com/1679892/181111494-0380bd1b-c07d-4004-9ab7-9c696b14bc27.png">
> 
> Would you mind taking a look?

Looking into this.

2022-07-28 19:46 UTC, nramadas approved these changes

2022-07-28 19:55 UTC, merged